name: whatch-releases
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "37 4 * * *" # run every day at 4:37am UTC

jobs:
  watch-releases:
    strategy:
      matrix:
        project:
          - operator-framework/operator-sdk
          - operator-framework/operator-registry
          - gmeghnag/koff
          - gmeghnag/omc
          - openshift-pipelines/opc
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vdemeester'
    steps:
      - name: ${{ matrix.project }}
        uses: git-for-windows/rss-to-issues@48c22f7f733ca11653f08694a2868fcda4246e89 # v0.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feed: https://github.com/${{ matrix.project }}/releases.atom
          prefix: "[${{ matrix.project }}]"
          dry-run: false
          max-age: 72h

